version: '3.7'

services:
  postgres:
    image: debezium/postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myselph
    ports:
      - 5432:5432